routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/*Route::get('/', function () {
    return view('welcome');
});*/

Auth::routes();

Route::get('/', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::get('products-list', [\App\Http\Controllers\ProductsController::class, 'index'])->name('products');

Route::get('products/{product}', [\App\Http\Controllers\ProductsController::class, 'show'])->name('products.show');

Route::get('products/{product}/images', [\App\Http\Controllers\ProductsController::class, 'galleryDisplay'])->name('products.images');

Route::get('categories', [\App\Http\Controllers\CategoriesController::class, 'index'])->name('categories');

Route::get('categories/{category}', [\App\Http\Controllers\CategoriesController::class, 'show'])->name('categories.show');

Route::delete('ajax/product-image/{image_id}', [\App\Http\Controllers\ProductImageController::class, 'destroy'])->name('ajax.products.image.delete');

//User profile routes
Route::namespace('User')->prefix('user')->name('user.')->middleware(['auth'])->group(function() {
    Route::get('profile', [\App\Http\Controllers\User\UserAccountController::class, 'index'])->name('profile');
    Route::get('{user}/edit', [\App\Http\Controllers\User\UserAccountController::class, 'edit'])->middleware('can:update,user')->name('edit');
    Route::put('{user}/update', [\App\Http\Controllers\User\UserAccountController::class, 'update'])->middleware('can:update,user')->name('update');

    Route::get('wishlist', [\App\Http\Controllers\User\WishlistController::class, 'index'])->name('wishlist');
});

//Admin routes
Route::namespace('Admin')->prefix('admin')->name('admin.')->middleware(['auth', 'admin'])->group(function() {

    Route::get('/', [\App\Http\Controllers\Admin\ControlPanelController::class, '__invoke'])->name('home');

    Route::name('products')->group(function(){
        Route::get('products', [\App\Http\Controllers\Admin\ProductsController::class, 'index']);
        Route::get('products/create', [\App\Http\Controllers\Admin\ProductsController::class, 'create'])->name('.create');
        Route::post('products', [\App\Http\Controllers\Admin\ProductsController::class, 'store'])->name('.store');
        Route::get('products/{product}/edit', [\App\Http\Controllers\Admin\ProductsController::class, 'edit'])->name('.edit');
        Route::put('products/{product}/update', [\App\Http\Controllers\Admin\ProductsController::class, 'update'])->name('.update');
        Route::delete('products/{product}', [\App\Http\Controllers\Admin\ProductsController::class, 'destroy'])->name('.delete');
    });

    Route::name('categories')->group(function() {
        Route::get('categories', [\App\Http\Controllers\Admin\CategoriesController::class, 'index']);
        Route::get('categories/create', [\App\Http\Controllers\Admin\CategoriesController::class, 'create'])->name('.create');
        Route::post('categories', [\App\Http\Controllers\Admin\CategoriesController::class, 'store'])->name('.store');
        Route::get('categories/{category}/edit', [\App\Http\Controllers\Admin\CategoriesController::class, 'edit'])->name('.edit');
        Route::put('categories/{category}/update', [\App\Http\Controllers\Admin\CategoriesController::class, 'update'])->name('.update');
        Route::delete('categories/{category}', [\App\Http\Controllers\Admin\CategoriesController::class, 'destroy'])->name('.delete');
    });

    Route::name('users')->group(function() {
        Route::get('users', [\App\Http\Controllers\Admin\UsersController::class, 'index']);
        Route::get('users/{user}', [\App\Http\Controllers\Admin\UsersController::class, 'show'])->name('users.show');
        Route::delete('users/{user}', [\App\Http\Controllers\Admin\UsersController::class, 'destroy'])->name('.delete');
    });

    Route::name('orders')->group(function () {
        Route::get('orders', [\App\Http\Controllers\Admin\OrdersController::class, 'index']);
        Route::get('orders/{order}/edit', [\App\Http\Controllers\Admin\OrdersController::class, 'edit'])->name('.edit');
        Route::delete('orders/{order}', [\App\Http\Controllers\Admin\OrdersController::class, 'destroy'])->name('.delete');
    });
});
//Shopping cart routing
Route::middleware('auth')->group(function () {
    Route::get('cart', [\App\Http\Controllers\CartController::class, 'index'])->name('cart');
    Route::post('cart/{product}/add', [\App\Http\Controllers\CartController::class, 'add'] )->name('cart.add');
    Route::post('cart/{product}/count/update', [\App\Http\Controllers\CartController::class, 'countUpdate'])->name('cart.count.update');
    Route::post('cart/product/delete', [\App\Http\Controllers\CartController::class, 'delete'])->name('cart.delete');

    Route::get('checkout', [\App\Http\Controllers\CheckoutController::class, '__invoke'])->name('checkout');
    Route::post('order', [\App\Http\Controllers\OrdersController::class, 'store'])->name('order.create');

    //Wishlist routing
    Route::get('wishlist/{product}/add', [\App\Http\Controllers\WishListController::class, 'add'])->name('wishlist.add');
    Route::delete('wishlist/{product}/delete', [\App\Http\Controllers\WishListController::class, 'delete'])->name('wishlist.delete');
});

resources/views/navigation/admin-menu.blade.php
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
                    <a class="navbar-brand" href="{{ route('admin.home') }}">Admin panel:</a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>

                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <ul class="navbar-nav mr-auto">
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    Products
                                </a>
                                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('admin.products') }}">Products list</a>
                                    <div class="dropdown-divider"></div>
                                    <a class="dropdown-item" href="{{ route('admin.products.create') }}">Create product</a>
                                </div>
                            </li>
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    Categories
                                </a>
                                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('admin.categories') }}">Categories list</a>
                                    <div class="dropdown-divider"></div>
                                    <a class="dropdown-item" href="{{ route('admin.categories.create') }}">Create category</a>
                                </div>
                            </li>
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    Orders
                                </a>
                                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('admin.orders') }}">Orders list</a>
                                </div>
                            </li>
                            <li class="nav-item active">
                                <a class="nav-link" href="#">Users<span class="sr-only">(current)</span></a>
                            </li>
                        </ul>
                        {{--<form class="form-inline my-2 my-lg-0">
                            <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
                            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
                        </form>--}}
                    </div>
                </nav>
            </div>
        </div>
    </div>

resources/views/navigation/front-menu.blade.php
<nav class="navbar navbar-expand-md navbar-light bg-info shadow-sm">
    <div class="container">
        <a class="navbar-brand" href="{{ url('/') }}">
            {{-- {{ config('app.name', 'Shop') }} --}}Home
        </a>
        <a class="navbar-brand" href="{{ url('/products-list') }}">
            {{-- {{ config('app.name', 'Shop') }} --}}All products
        </a>
        <a class="navbar-brand" href="{{ url('/categories') }}">
            {{-- {{ config('app.name', 'Shop') }} --}}Categories
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <!-- Left Side Of Navbar -->
            <ul class="navbar-nav mr-auto">

            </ul>

            <!-- Right Side Of Navbar -->
            <ul class="navbar-nav ml-auto">
                <!-- Authentication Links -->
                @guest
                    @if (Route::has('login'))
                        <li class="nav-item">
                            <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                        </li>
                    @endif

                    @if (Route::has('register'))
                        <li class="nav-item">
                            <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                        </li>
                    @endif
                @else
                    <li class="nav-item">
                        <a class="nav-link" href="{{ route('cart') }}">
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-cart3" viewBox="0 0 16 16">
                                <path d="M0 1.5A.5.5 0 0 1 .5 1H2a.5.5 0 0 1 .485.379L2.89 3H14.5a.5.5 0 0 1 .49.598l-1 5a.5.5 0 0 1-.465.401l-9.397.472L4.415 11H13a.5.5 0 0 1 0 1H4a.5.5 0 0 1-.491-.408L2.01 3.607 1.61 2H.5a.5.5 0 0 1-.5-.5zM3.102 4l.84 4.479 9.144-.459L13.89 4H3.102zM5 12a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm7 0a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm-7 1a1 1 0 1 1 0 2 1 1 0 0 1 0-2zm7 0a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"/>
                            </svg>
                        @if(Cart::instance('cart')->count() > 0)<strong>{{ Cart::instance('cart')->count() }}</strong>@endif</a>
                    </li>
                    <li class="nav-item dropdown">
                        <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                            {{ Auth::user()->name }}
                        </a>
                        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                            @if(Auth::user()->role()->first()->isAdmin())
                                <a class="dropdown-item" href="{{ route('admin.home') }}">
                                    {{__('Admin Control Panel') }}
                                </a>
                            @endif
                            <a class="dropdown-item" href="{{ route('user.profile') }}">
                                    {{ __('Your profile') }}
                            </a>
                            <a class="dropdown-item" href="{{ route('logout') }}"
                               onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                {{ __('Logout') }}
                            </a>
                            <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                                @csrf
                            </form>
                        </div>
                    </li>
                @endguest
            </ul>
        </div>
    </div>
</nav>