routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/*Route::get('/', function () {
    return view('welcome');
});*/

Auth::routes();

Route::get('/', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::get('products-list', [\App\Http\Controllers\ProductsController::class, 'index'])->name('products');

Route::get('products/{product}', [\App\Http\Controllers\ProductsController::class, 'show'])->name('products.show');

Route::get('products/{product}/images', [\App\Http\Controllers\ProductsController::class, 'galleryDisplay'])->name('products.images');

Route::get('categories', [\App\Http\Controllers\CategoriesController::class, 'index'])->name('categories');

Route::get('categories/{category}', [\App\Http\Controllers\CategoriesController::class, 'show'])->name('categories.show');

Route::delete('ajax/product-image/{image_id}', [\App\Http\Controllers\ProductImageController::class, 'destroy'])->name('ajax.products.image.delete');

//User profile routes
Route::namespace('User')->prefix('user')->name('user.')->middleware(['auth'])->group(function() {
    Route::get('profile', [\App\Http\Controllers\User\UserAccountController::class, 'index'])->name('profile');
    Route::get('{user}/edit', [\App\Http\Controllers\User\UserAccountController::class, 'edit'])->middleware('can:update,user')->name('edit');
    Route::put('{user}/update', [\App\Http\Controllers\User\UserAccountController::class, 'update'])->middleware('can:update,user')->name('update');

    Route::get('wishlist', [\App\Http\Controllers\User\WishlistController::class, 'index'])->name('wishlist');
});

//Admin routes
Route::namespace('Admin')->prefix('admin')->name('admin.')->middleware(['auth', 'admin'])->group(function() {

    Route::get('/', [\App\Http\Controllers\Admin\ControlPanelController::class, '__invoke'])->name('home');

    Route::name('products')->group(function(){
        Route::get('products', [\App\Http\Controllers\Admin\ProductsController::class, 'index']);
        Route::get('products/create', [\App\Http\Controllers\Admin\ProductsController::class, 'create'])->name('.create');
        Route::post('products', [\App\Http\Controllers\Admin\ProductsController::class, 'store'])->name('.store');
        Route::get('products/{product}/edit', [\App\Http\Controllers\Admin\ProductsController::class, 'edit'])->name('.edit');
        Route::put('products/{product}/update', [\App\Http\Controllers\Admin\ProductsController::class, 'update'])->name('.update');
        Route::delete('products/{product}', [\App\Http\Controllers\Admin\ProductsController::class, 'destroy'])->name('.delete');
    });

    Route::name('categories')->group(function() {
        Route::get('categories', [\App\Http\Controllers\Admin\CategoriesController::class, 'index']);
        Route::get('categories/create', [\App\Http\Controllers\Admin\CategoriesController::class, 'create'])->name('.create');
        Route::post('categories', [\App\Http\Controllers\Admin\CategoriesController::class, 'store'])->name('.store');
        Route::get('categories/{category}/edit', [\App\Http\Controllers\Admin\CategoriesController::class, 'edit'])->name('.edit');
        Route::put('categories/{category}/update', [\App\Http\Controllers\Admin\CategoriesController::class, 'update'])->name('.update');
        Route::delete('categories/{category}', [\App\Http\Controllers\Admin\CategoriesController::class, 'destroy'])->name('.delete');
    });

    Route::name('users')->group(function() {
        Route::get('users', [\App\Http\Controllers\Admin\UsersController::class, 'index']);
        Route::get('users/{user}', [\App\Http\Controllers\Admin\UsersController::class, 'show'])->name('users.show');
        Route::delete('users/{user}', [\App\Http\Controllers\Admin\UsersController::class, 'destroy'])->name('.delete');
    });

    Route::name('orders')->group(function () {
        Route::get('orders', [\App\Http\Controllers\Admin\OrdersController::class, 'index']);
        Route::get('orders/{order}/edit', [\App\Http\Controllers\Admin\OrdersController::class, 'edit'])->name('.edit');
        Route::delete('orders/{order}', [\App\Http\Controllers\Admin\OrdersController::class, 'destroy'])->name('.delete');
    });
});
//Shopping cart routing
Route::middleware('auth')->group(function () {
    Route::get('cart', [\App\Http\Controllers\CartController::class, 'index'])->name('cart');
    Route::post('cart/{product}/add', [\App\Http\Controllers\CartController::class, 'add'] )->name('cart.add');
    Route::post('cart/{product}/count/update', [\App\Http\Controllers\CartController::class, 'countUpdate'])->name('cart.count.update');
    Route::post('cart/product/delete', [\App\Http\Controllers\CartController::class, 'delete'])->name('cart.delete');

    Route::get('checkout', [\App\Http\Controllers\CheckoutController::class, '__invoke'])->name('checkout');
    Route::post('order', [\App\Http\Controllers\OrdersController::class, 'store'])->name('order.create');

    //Wishlist routing
    Route::get('wishlist/{product}/add', [\App\Http\Controllers\WishListController::class, 'add'])->name('wishlist.add');
    Route::delete('wishlist/{product}/delete', [\App\Http\Controllers\WishListController::class, 'delete'])->name('wishlist.delete');
});

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var string[]
     */
    protected $fillable = [
        'name',
        'surname',
        'birthday_date',
        'email',
        'phone_number',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function role()
    {
        return $this->belongsTo(Role::class);
    }

    public function orders()
    {
        return $this->hasMany(Order::class);
    }

    public function instanceCartName()
    {
        $userName = [
            $this->id,
            $this->surname
        ];

        return implode('_', $userName);
    }

    public function wish()
    {
        return $this->belongsToMany(
            \App\Models\Product::class,
            'wishlist',
            'user_id',
            'product_id'
        );
    }

    public function addToWish(Product $product)
    {
        return $this->wish()->attach($product);
    }

    public function removeFromWish(Product $product)
    {
        return $this->wish()->detach($product);
    }
}

app/Http/Controllers/Admin/UsersController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class UsersController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    /*public function create()
    {
        //
    }
    */

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    /*public function store(Request $request)
    {
        //
    }
    */
    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    /*public function edit($id)
    {
        //
    }
    */
    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    /*public function update(Request $request, $id)
    {
        //
    }
    */
    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/User/UserAccountController.php
<?php

namespace App\Http\Controllers\User;

use App\Http\Controllers\Controller;
use App\Http\Requests\UserUpdateRequest;
use App\Models\User;
use Illuminate\Http\Request;

class UserAccountController extends Controller
{

    public function index()
    {
        $user = User::with('role')->find(auth()->user()->id);
        return view('user/profile', compact('user'));
    }

    public function edit(User $user)
    {
        return view('user/edit', compact('user'));
    }


    public function update(UserUpdateRequest $request, User $user)
    {
        $user->update($request->validated());
        return redirect(route('user.profile'))->with('status', 'Profile data was successfully updated!');
    }

    /*public function show(Request $request)
    {
        $user = Auth::user();

        return view('user/profile', compact( 'user'));

    }*/

}

app/Http/Controllers/User/WishlistController.php
<?php

namespace App\Http\Controllers\User;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class WishlistController extends Controller
{
    public function index()
    {
        return view('user/wishlist/index');
    }
}

resources/views/user/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                @include('user.parts.user-nav')
            </div>
            <div class="col-md-12">
                <h3 class="text-center">{{ __('Edit Profile Data') }}</h3>
                <hr>
            </div>
            <div class="col-md-12">
                @if ($errors->any())
                    <div class="alert alert-danger">
                        <strong>Whoops!</strong> There were some problems with your input.<br><br>
                        <ul>
                            @foreach ($errors->all() as $error)
                                <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div>
                @endif
            </div>
            <div class="col-md-8">
                <form method="POST" action="{{ route('user.update', $user) }}">
                    @csrf
                    @method('PUT')
                    <div class="form-group row">
                        <label for="name" class="col-md-4 col-form-label text-md-right">{{ __('Name') }}</label>
                        <div class="col-md-6">
                            <input id="role_id"
                                   type="hidden"
                                   class="form-control @error('role_id') is-invalid @enderror"
                                   name="role_id"
                                   value="{{ $user->role_id }}"
                                   autocomplete="role_id"
                                   autofocus>
                            <input id="name"
                                   type="text"
                                   class="form-control @error('name') is-invalid @enderror"
                                   name="name" value="{{ $user->name }}"
                                   autocomplete="name"
                                   autofocus>
                        </div>
                    </div>

                    <div class="form-group row">
                        <label for="surname" class="col-md-4 col-form-label text-md-right">{{ __('Surname') }}</label>
                        <div class="col-md-6">
                            <input id="surname"
                                   type="text"
                                   class="form-control @error('surname') is-invalid @enderror"
                                   name="surname"
                                   value="{{$user->surname }}"
                                   autocomplete="surname"
                                   autofocus>
                        </div>
                    </div>

                    <div class="form-group row">
                        <label for="email" class="col-md-4 col-form-label text-md-right">{{ __('E-Mail Address') }}</label>
                        <div class="col-md-6">
                            <input id="email"
                                   type="email"
                                   class="form-control @error('email') is-invalid @enderror"
                                   name="email"
                                   value="{{ $user->email }}"
                                   autocomplete="email">
                        </div>
                    </div>

                    <div class="form-group row">
                        <label for="phone" class="col-md-4 col-form-label text-md-right">{{ __('Phone Number') }}</label>
                        <div class="col-md-6">
                            <input id="phone_number"
                                   type="tel"
                                   class="form-control @error('phone_number') is-invalid @enderror"
                                   name="phone_number"
                                   value="{{ $user->phone_number }}">
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="birthday" class="col-md-4 col-form-label text-md-right">{{ __('Birthday') }}</label>
                        <div class="col-md-6">
                            <input id="birthday_date"
                                   type="date"
                                   class="form-control @error('birthday_date') is-invalid @enderror"
                                   name="birthday_date"
                                   value="{{ $user->birthday_date }}">
                        </div>
                    </div>
                    <div class="form-group row mb-0">
                        <div class="col-md-6 offset-md-4">
                            <button type="submit" class="btn btn-success">
                                {{ __('Update data') }}
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/user/profile.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                @include('user.parts.user-nav')
            </div>
            <div class="col-md-8">
                <div class="mb-3"><span class="text-muted">{{ __('User profile:') }}</span>
                    Hello, {{ $user->name . " " . $user->surname }} !
                </div>
            </div>
            <div class="col-md-12">
                <table class="table table-secondary table-borderless table-sm">
                    <thead class="table-info">
                    <tr>
                        <th class="text-center" scope="col"> Name </th>
                        <th class="text-center" scope="col"> Value <th>
                    </tr>
                    </thead>
                    <tbody>
                    <tr>
                        <td scope="row" class="text-center">{{__('Role')}}</td>
                        <td class="text-center"> {{ $user->role->name }} </td>
                    </tr>
                    <tr>
                        <td scope="row" class="text-center">{{__('Name')}}</td>
                        <td class="text-center"> {{ $user->name }} </td>
                    </tr>
                    <tr>
                        <td scope="row" class="text-center">{{__('Surname')}}</td>
                        <td class="text-center"> {{ $user->surname }} </td>
                    </tr>
                    <tr>
                        <td scope="row" class="text-center">{{__('E-Mail')}}</td>
                        <td class="text-center"> {{ $user->email }} </td>
                    </tr>
                    <tr>
                        <td scope="row" class="text-center">{{__('Birthday')}}</td>
                        <td class="text-center"> {{ $user->birthday_date }} </td>
                    </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
@endsection